"""fix_provider_configs_schema_final

Revision ID: 41045357b510
Revises: a4dde98cb82e
Create Date: 2026-01-02 22:36:00.225448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41045357b510'
down_revision: Union[str, Sequence[str], None] = 'a4dde98cb82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        # We don't explicitly drop constraints here to avoid KeyError.
        # Alembic's batch_alter_table will recreate the table based on the Target Metadata.
        # Since Target Metadata (from models.py) no longer has the unique constraints,
        # the recreated table will not have them either.
        batch_op.alter_column('provider_kind', existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provider_configs_provider_kind', ['provider_kind'])
        batch_op.create_unique_constraint('uq_provider_configs_stage_type', ['stage_type'])
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('product_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_configs_key'), type_='unique')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payments_yookassa_payment_id'), type_='unique')

    with op.batch_alter_table('content_policies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_content_policies_policy_type'), type_='unique')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
