"""add_order_status_and_update_payments

Revision ID: 681100486a0e
Revises: 1371acf29a56
Create Date: 2026-01-02 17:59:36.086381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681100486a0e'
down_revision: Union[str, Sequence[str], None] = '1371acf29a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=False, server_default='RUB'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'currency')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
