"""remove_provider_kind_unique

Revision ID: 9030d45b63be
Revises: 41045357b510
Create Date: 2026-01-02 22:48:48.675937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9030d45b63be'
down_revision: Union[str, Sequence[str], None] = '41045357b510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        # Просто вызываем пересоздание таблицы. Alembic увидит, что в Target Metadata
        # (которая загружена в env.py через Base.metadata) больше нет уникальности,
        # и создаст новую таблицу без нее.
        batch_op.alter_column('provider_kind', existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_provider_configs_provider_kind', ['provider_kind'])

    # ### end Alembic commands ###
