"""update_provider_configs_for_stage_types_batch

Revision ID: a4dde98cb82e
Revises: 681100486a0e
Create Date: 2026-01-02 20:04:01.976305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4dde98cb82e'
down_revision: Union[str, Sequence[str], None] = '681100486a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('content_policies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('product_configs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('api_key_encrypted', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('models_cache', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('models_cache_updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # 1. Fill stage_type for existing records to avoid NOT NULL and UNIQUE violation during batch migration
    # We use IDs to ensure uniqueness if multiple records exist
    op.execute("UPDATE provider_configs SET stage_type = 'POEM' WHERE id = 1")
    op.execute("UPDATE provider_configs SET stage_type = 'VOICE' WHERE id = 2")
    op.execute("UPDATE provider_configs SET stage_type = 'SONG' WHERE id = 3")
    op.execute("UPDATE provider_configs SET stage_type = 'CLIP' WHERE id = 4")
    # For any others, use a random-ish string to avoid unique constraint failure
    op.execute("UPDATE provider_configs SET stage_type = 'OLD_' || id WHERE stage_type IS NULL")

    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.alter_column('stage_type', existing_type=sa.String(), nullable=False)
        batch_op.create_unique_constraint('uq_provider_configs_stage_type', ['stage_type'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_provider_configs_stage_type', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('models_cache_updated_at')
        batch_op.drop_column('models_cache')
        batch_op.drop_column('model')
        batch_op.drop_column('api_key_encrypted')
        batch_op.drop_column('stage_type')

    with op.batch_alter_table('product_configs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('content_policies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
