COMMON = {
    "save": "Сохранить",
    "save_changes": "Сохранить изменения",
    "saving": "Сохранение...",
    "saved": "✅ Изменения сохранены.",
    "cancel": "Отмена",
    "confirm": "Подтвердить",
    "delete": "Удалить",
    "error": "Ошибка",
    "try_again": "Попробуйте ещё раз.",
    "back_to_list": "Вернуться к списку",
    "confirm_title": "Подтвердите действие",
    "confirm_text": "Вы уверены, что хотите {action}?",
    "confirm_impact": "Это может повлиять на обработку текущих заказов.",
    "yes_continue": "Да, продолжить",
}

PROVIDER = {
    "title": "Конфигурация LLM",
    "section_key": "Провайдер и API-ключ",
    "subtitle_key": "Выберите провайдера и вставьте ключ доступа.",
    "provider_label": "Провайдер",
    "provider_placeholder": "Выберите провайдера",
    "key_label": "API-ключ",
    "key_placeholder": "Вставьте API-ключ",
    "key_helper": "Ключ хранится безопасно. Можно заменить в любой момент.",
    "save_key": "Сохранить провайдер и ключ",
    "check_key": "Проверить ключ",
    "models_title": "Модели",
    "models_subtitle": "Укажите модели для текста и изображений (если нужно).",
    "text_model": "Текстовая модель",
    "text_model_placeholder": "Выберите модель для текста",
    "vision_model": "Модель для изображений",
    "vision_model_placeholder": "Выберите модель для изображений",
    "creativity": "Креативность",
    "creativity_helper": "Низкая — точнее, высокая — смелее формулировки.",
    "save_models": "Сохранить модели",
    "current_config": "Текущая конфигурация",
    "history_title": "История ключей",
    "history_empty": "История ключей пуста",
}

ORDER = {
    "title": "Заказ № {id}",
    "summary": "Сводка",
    "created": "Создан",
    "updated": "Обновлён",
    "status": "Статус заказа",
    "payment": "Оплата",
    "total": "Итоговая сумма",
    "provider": "Провайдер",
    "model": "Модель",
    "stages": "Этапы",
    "stages_subtitle": "Здесь виден прогресс по каждому этапу заказа.",
    "stage": "Этап",
    "price": "Цена",
    "actions": "Действия",
    "restart": "Перезапустить",
    "restart_helper": "Запустит этап заново. Текущий результат может быть перезаписан.",
    "cancel_stage": "Отменить",
    "cancel_helper": "Остановит выполнение этапа.",
    "no_stages_title": "Этапы не добавлены",
    "no_stages_text": "Создайте этапы или проверьте настройки продукта.",
    "result_pending": "Результат появится после завершения этапа.",
}

STATUS_LABELS = {
    "stage": {
        "pending": "В ожидании",
        "queued": "В очереди",
        "processing": "В работе",
        "running": "В работе",
        "completed": "Готово",
        "success": "Готово",
        "failed": "Ошибка",
        "error": "Ошибка",
        "canceled": "Отменён",
        "cancelled": "Отменён",
        "retrying": "Повторная попытка",
        "paused": "Пауза",
    },
    "order": {
        "new": "Новый",
        "paid": "Оплачен",
        "in_progress": "В обработке",
        "completed": "Завершён",
        "failed": "Ошибка",
        "canceled": "Отменён",
        "waiting_payment": "Ожидает оплату",
    },
    "key": {
        "active": "Активен",
        "inactive": "Отключён",
        "needs_check": "Требует проверки",
        "invalid": "Не работает",
        "quota_exceeded": "Квота исчерпана",
        "rate_limited": "Слишком много запросов",
    },
    "payment": {
        "unpaid": "Не оплачено",
        "paid": "Оплачено",
        "refunded": "Возврат оформлен",
        "chargeback": "Спор/чарджбек",
    }
}